version: '3.8'

services:
  php:
    build: ./php
    container_name: php
    ports:
      - "38080:80"
    volumes:
      - ./app:/var/www/html
      - ./app/uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: meishi_db
      POSTGRES_USER: meishi_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "25432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:

